apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id
  name: {{ include "register-pipeline.secret-name" . }}
  labels:
    # so we know what type it is
    # available types: certificate, secretFile, secretText, usernamePassword, basicSSHUserPrivateKey
    # see https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "Git credentials for {{ .Values.git.url }} from kubernetes"
type: Opaque
stringData:
  url: {{ .Values.git.url }}
  username: {{ .Values.git.username }}
  {{- if .Values.git.password -}}
  password: {{ .Values.git.password }}
  {{- end }}
  {{- if .Values.git.passphrase -}}
  passphrase: {{ .Values.git.passphrase }}
  {{- end }}
  {{- if .Values.git.privateKeyFile -}}
  privateKey: |
    {{ .Files.Get .Values.git.privateKeyFile  | indent 4 }}
  {{- end }}
